stages:
  - deploy

deploy:
  stage: deploy
  script:
    - chmod +x gradlew
    - ./gradlew setupCiWorkspace
    - ./gradlew build
  only:
  - master
  - tags
  tags:
    - Java8
  artifacts:
    paths:
    - "build/libs/ForgeCraftingManager*.jar"
